using System;
using System.Collections.Generic;

/// <summary>
/// All player-facing strings go through Loc.Get(key, args). Today it reads a built-in English table;
/// later the body of Get() can be swapped for the Unity Localization package without touching any screen.
/// Args are string.Format arguments ({0}, {1:F1}...).
/// </summary>
public static class Loc
{
    private static readonly Dictionary<string, string> English = new Dictionary<string, string>
    {
        // Systems dock tabs
        { "ui.mode.sensors",    "SENSORS" },
        { "ui.mode.navigation", "NAVIGATION" },
        { "ui.mode.comms",      "COMMS" },
        { "ui.mode.systems",    "SYSTEMS" },
        { "ui.mode.atlas",      "ATLAS" },

        { "ui.tab.nav",      "NAV" },
        { "ui.tab.maneuver", "MANOEUVERS" },
        { "ui.tab.jump",    "JUMP" },
        { "ui.tab.wake",    "WAKE" },
        { "ui.tab.reactor", "REACTOR" },
        { "ui.tab.data",    "DATA" },
        { "ui.tab.tx",      "TX" },
        { "ui.tab.node",    "NODE" },

        // Sensor console modes
        { "ui.screen.waterfall",     "WATERFALL" },
        { "ui.screen.imager",        "IMAGER" },
        { "ui.screen.spectrometer",  "SPECTROMETER" },
        { "ui.screen.system",        "CONTACTS" },
        { "ui.screen.radar",         "RADAR" },
        { "ui.screen.notfitted",     "{0}: NOT FITTED\n\nThis probe doesn't carry one. Fit it at the next refit." },
        { "ui.screen.power.on",      "SENSOR ON" },
        { "ui.screen.power.off",     "SENSOR OFF" },

        // Radar
        { "ui.radar.mode.sweep",       "SWEEP" },
        { "ui.radar.mode.track",       "TRACK" },
        { "ui.radar.beam",             "BEAM +/-" },
        { "ui.radar.beam.value",       "{0:F0}deg" },
        { "ui.radar.target",           "TARGET: {0}" },
        { "ui.radar.target.none",      "TARGET: none selected" },
        { "ui.radar.fire",             "FIRE PING" },
        { "ui.radar.reping",           "RE-PING" },
        { "ui.radar.cancel",           "CANCEL" },
        { "ui.radar.pinging",          "PINGING... eta ~{0:F0}s" },
        { "ui.radar.noreturn",         "no return" },
        { "ui.radar.result.range",     "RANGE {0}" },
        { "ui.radar.result.rangerate", "RANGE {0}   RATE {1:+0.00;-0.00} km/s" },
        { "ui.radar.result.rangerate.brg", "RANGE {0}   RATE {1:+0.00;-0.00} km/s   @ {2:000.0}" },
        { "ui.radar.result.moved",     "(track moved: not filed)" },
        { "ui.radar.result.sweep",     "SWEEP COMPLETE: {0} return(s)" },
        { "ui.radar.scale",            "SCALE" },
        { "ui.radar.rings",            "rings every {0}   north up" },
        { "ui.radar.returns",          "returns on scope: {0}" },
        { "ui.radar.hint.sweep",       "Click the scope to aim the sweep. Click a return to mark it as a track." },
        { "ui.radar.hint.track",       "Pings the selected track's bearing for a precise range and range rate. Click a track line to select it." },
        { "ui.radar.trackfull",        "Track list full: drop a track first." },

        // Manual aiming
        { "ui.aim.tilt",           "TILT" },
        { "ui.aim.tilt.value",     "{0:+0.0;-0.0}deg fan +/-{1:0}" },
        { "ui.aim.cursor",         "CUR {0:000.0}" },
        { "ui.aim.mark",           "MARK" },
        { "ui.aim.move",           "CORRECT" },
        { "ui.wf.zoom",            "ZOOM" },
        { "ui.wf.zoom.value",      "x{0:0}  ({1:0.#}deg)" },
        { "ui.wf.center",          "CTR" },
        { "ui.spec.zoom.value",    "x{0}  ({1:0}-{2:0} nm)" },
        { "ui.spec.full",          "FULL" },
        { "ui.spec.doppler",       "DOPPLER  v_r {0:+0.0;-0.0} km/s  +/-{1:0.0}   (shift {2:+0.000;-0.000} nm at 600 nm)" },
        { "ui.wf.zoomhint",        "wheel = zoom, drag = pan" },
        { "ui.track.hold.img",     "HOLD img" },
        { "ui.track.hold.rad",     "HOLD rad" },
        { "ui.aim.el",             "EL" },
        { "ui.radar.el.manual",    "{0:+0.0;-0.0}deg  (fan +/-{1:0.#})" },
        { "ui.radar.el.track",     "track {0:+0.0;-0.0}deg +/-{1:0.0#}" },
        { "ui.radar.el.nofix",     "no track EL: manual {0:+0.0;-0.0}deg (fan +/-{1:0.#})" },
        { "ui.imager.aim",         "AZ {0:000.0}  EL {1:+00.0;-00.0}" },
        { "ui.imager.aim.trk",     "AZ {0:000.0}  EL {1:+00.0;-00.0} (trk)" },
        { "ui.imager.fix",         "FIX" },
        { "ui.imager.fix.notrack", "FIX: select or slave a track first" },
        { "ui.imager.fix.nothing", "FIX: nothing bright near the crosshair" },
        { "ui.imager.fix.offbearing", "FIX: blob is {1:+0.0;-0.0}deg off {0}'s bearing" },
        { "ui.imager.fix.ok",      "FIX {0}: EL {1:+0.00;-0.00} +/-{2:0.00#}" },
        { "ui.imager.fix.clipped", "FIX: the blob runs off the frame, widen the FOV" },
        { "ui.imager.fix.worse",   "FIX {0}: track already has a better EL" },
        { "ui.spec.noel",          "{0}: NO ELEVATION - FIX it with the imager or a radar TRACK ping" },
        { "ui.spec.coarseel",      "{0}: EL too coarse (+/-{1:0.0} > {2:0.0}deg) - refine to point the slit" },
        { "ui.system.el",          "EL {0:+0.0;-0.0} +/-{1:0.0#} ({2})" },
        { "ui.system.noel",        "EL --" },

        // Imager / spectrometer targeting (tracks only)
        { "ui.imager.free",        "FREE AIM" },
        { "ui.imager.track",       "TRK {0}" },
        { "ui.imager.lost",        "TRK {0} (searching)" },
        { "ui.spec.none",          "NO TARGET: lock a tracked contact" },
        { "ui.spec.lost",          "{0}: TRACK LOST" },
        { "ui.spec.nosignal",      "{0}: NO SIGNAL in slit" },
        { "ui.spec.analyzing",     "{0}: analyzing... {1:F0}%" },
        { "ui.spec.id",            "{0}: ID {1}" },
        { "ui.spec.id.blend",      "{0}: ID {1} (BLEND)" },

        // System overview table (tracks only)
        { "ui.system.none",        "No contacts. Mark a bearing on the waterfall or a radar return." },
        { "ui.system.col.name",    "TRACK" },
        { "ui.system.col.status",  "STATUS" },
        { "ui.system.col.brg",     "BRG" },
        { "ui.system.col.range",   "RANGE" },
        { "ui.system.col.class",   "CLASS" },
        { "ui.system.col.detail",  "DETAIL" },
        { "ui.system.lock",        "LOCK" },
        { "ui.system.search",      "SEARCH" },
        { "ui.system.brg",         "{0:000.0} deg" },
        { "ui.system.range",       "{0} +/-{1:F0}%" },
        { "ui.system.norange",     "--" },
        { "ui.system.unknown",     "unknown" },
        { "ui.system.analyzing",   "analyzing" },
        { "ui.system.airless",     "airless  {0:F0} K" },
        { "ui.system.envelope",    "envelope" },
        { "ui.system.pressure",    "{0:0.##} atm" },
        { "ui.system.star.short",  "{0:F0} K  [Fe/H] {1:+0.00;-0.00}  {2:F1} Gyr" },
        { "ui.system.star.long",   "Teff {0:F0} K   [Fe/H] {1:+0.00;-0.00} dex   age {2:F1} Gyr" },
        { "ui.system.temps",       "Teq {0:F0} K   surface {1:F0} K" },
        { "ui.system.atmo.none",   "Atmosphere: none detected" },
        { "ui.system.atmo",        "Atmosphere ({0:0.##} atm):" },
        { "ui.system.atmo.envelope","Envelope:" },
        { "ui.system.comp",        "Composition:" },
        { "ui.system.class",       "CLASS {0}" },
        { "ui.system.blend",       "BLENDED SPECTRUM - another source was in the slit" },
        { "ui.system.rrate",       "RR {0:+0.00;-0.00} km/s" },
        { "ui.system.selecthint",  "Select a contact for details." },
        { "ui.system.hint.lock",   "Searching: the tracker needs a few detections on this bearing to lock it." },
        { "ui.system.hint.spec",   "Locked. Get a fine EL (imager FIX or radar TRACK ping), then SPECTROMETER (SEL) to identify it. RADAR gives range." },
        { "ui.system.hint.dwell",  "Spectrometer analysis in progress - keep it locked to finish." },

        // Status bar
        { "ui.power",    "POWER" },
        { "ui.hydrogen", "HYDROGEN" },
        { "ui.storage",  "STORAGE" },
        { "ui.run",      "RUN {0} - MET {1}" },
        { "ui.system",   "SYSTEM {0}" },
        { "ui.net",      "{0:+0.00;-0.00} /day\nsolar +{1:F2}  reactor +{3:F2}  load -{2:F2}" },
        { "ui.pause",    "II" },

        // Tracks
        { "ui.tracks",         "TRACKS" },
        { "ui.tracks.collapse", "HIDE" },
        { "ui.tracks.expand",   "SHOW" },
        { "ui.tracks.none",    "No contact." },
        { "ui.track.bearing",  "{0:F1} deg" },
        { "ui.track.rate",     "{0:+0.00;-0.00} deg/d" },
        { "ui.track.norate",   "-- deg/d" },
        { "ui.track.quality",  "{0:F0}%" },
        { "ui.track.searching","searching..." },
        { "ui.track.drop",     "x" },
        { "ui.track.nextname",     "NEXT" },
        { "ui.track.nextnamehint", "name" },
        { "ui.track.markhint",     "click waterfall: mark, or correct selected" },
        { "ui.heading.tick",       "HDG" },

        { "ui.track.range",    "R {0} +/-{1:F0}%" },
        { "ui.track.norange",  "R --" },

        // Orbit
        { "ui.orbit",          "ORBIT" },
        { "ui.orbit.target",   "TARGET ORBIT" },
        { "ui.orbit.none",     "No stable orbit." },
        { "ui.orbit.escape",   "ESCAPE trajectory from {0}" },
        { "ui.orbit.peri",     "PERI {0}   (hyperbolic)" },
        { "ui.orbit.vinf",     "v-infinity {0:F2} km/s" },
        { "ui.orbit.primary",  "orbiting {0}" },
        { "ui.orbit.apsides",  "PERI {0}   APO {1}" },
        { "ui.orbit.shape",    "e {0:F3}   i {1:F1} deg" },
        { "ui.orbit.period",   "period {0:F1} d" },
        { "ui.orbit.nu",       "true anomaly {0:F0} deg" },

        // Maneuver node planning
        { "ui.node.time",             "T+ {0}" },
        { "ui.node.now",              "NOW" },
        { "ui.node.prograde",         "PROGRADE {0:+0.00;-0.00} km/s" },
        { "ui.node.normal",           "NORMAL {0:+0.00;-0.00} km/s" },
        { "ui.node.preview.none",     "No preview - orbit not valid." },
        { "ui.node.preview.shape",    "e {0:F3}   i {1:F1} deg   period {2:F1} d" },
        { "ui.node.arm",              "ARM" },
        { "ui.node.clear",            "CLEAR" },
        { "ui.node.warp",             "WARP TO NODE" },
        { "ui.node.warp.cancel",      "CANCEL WARP" },
        { "ui.node.queue",            "Node in {0}   dv {1:F2} km/s   ({2} queued)" },
        { "ui.node.queue.none",       "No node armed." },
        { "ui.node.dvbudget",         "dv budget {0:F2} km/s   queued {1:F2} km/s   margin {2:+0.00;-0.00} km/s" },
        { "ui.node.arm.hint",         "ARM queues the hand-set burn above (set PROGRADE/NORMAL first). PLOT TRANSFER and CREATE NODES (NAV tab) queue their own burns immediately - no separate ARM needed, and ARM here would replace them." },
        { "ui.node.target",           "TARGET: {0}" },
        { "ui.node.target.none",      "TARGET: none selected" },
        { "ui.node.transfer",         "PLOT + ARM TRANSFER" },
        { "ui.node.transfer.header",  "TRANSFER" },

        // NAV screen
        { "ui.nav.open",         "NAV" },
        { "ui.nav.title",        "NAVIGATION" },
        { "ui.nav.back",         "BACK" },
        { "ui.nav.notfitted",    "NAV COMPUTER: NOT FITTED\n\nThis probe carries no nav computer, so there is no graphical plot - fit one at the next refit. Orbit and maneuver data still read out as text (ORBIT / NODE)." },
        { "ui.nav.none",         "No stable orbit to plot." },
        { "ui.nav.primary",      "PRIMARY   {0}" },
        { "ui.nav.shape",        "a {0}   e {1:F3}" },
        { "ui.nav.incl",         "INCLINATION   {0:F1} deg" },
        { "ui.nav.period",       "PERIOD   {0:F1} d" },
        { "ui.nav.nu",           "TRUE ANOMALY   {0:F0} deg" },
        { "ui.nav.zoomin",       "ZOOM IN" },
        { "ui.nav.zoomout",      "ZOOM OUT" },
        { "ui.nav.label.pe",     "Pe" },
        { "ui.nav.label.ap",     "Ap" },
        { "ui.nav.label.an",     "AN" },
        { "ui.nav.label.dn",     "DN" },
        { "ui.nav.label.ship",   "SHIP" },
        { "ui.nav.layer.catalogue", "CATALOGUE" },
        { "ui.nav.layer.tracks",    "TRACKS" },
        { "ui.nav.transfer.header",      "TRANSFER" },
        { "ui.nav.transfer.none",        "TARGET   none (click a track)" },
        { "ui.nav.transfer.target",      "TARGET   {0}" },
        { "ui.nav.transfer.unavailable", "No fix yet - range unresolved (needs more tracking time), or no stable own orbit." },
        { "ui.nav.transfer.phase",       "PHASE {0:F0} deg / needs {1:F0} deg" },
        { "ui.nav.transfer.window.open", "WINDOW OPEN NOW" },
        { "ui.nav.transfer.window.wait", "WINDOW IN {0}" },
        { "ui.nav.transfer.dv",          "dv {0:F2} + {1:F2} km/s   ToF {2:F1} d" },
        { "ui.nav.transfer.create",      "CREATE + ARM NODES" },

        { "ui.nav.timeline",         "TIMELINE" },
        { "ui.nav.timeline.warpto",  "WARP TO" },
        { "ui.nav.timeline.row",     "T- {0}   {1}" },
        { "ui.nav.event.periapsis",  "Periapsis passage" },
        { "ui.nav.event.periapsis.impact", "IMPACT: periapsis below surface" },
        { "ui.nav.event.apoapsis",   "Apoapsis passage" },
        { "ui.nav.event.burn",       "Burn #{0} ({1:F2} km/s)" },

        // Maneuver
        { "ui.maneuver",  "MANEUVER" },
        { "ui.heading",   "HEADING {0:F1} deg" },
        { "ui.velocity",  "VELOCITY {0:F2} km/s   BRG {1:F1} deg" },
        { "ui.burnsize",  "BURN SIZE (km/s)" },
        { "ui.burn.fwd",  "BURN" },
        { "ui.burn.retro","RETRO" },
        { "ui.burn.cost", "Cost {0:F1} H   (have {1:F1})" },

        // Jump
        { "ui.jump",       "JUMP DRIVE" },
        { "ui.jump.none",  "No system in range." },
        { "ui.jump.at",    "AT {0}   -   {1:F1} ly from home" },
        { "ui.jump.home",  "HOME" },
        { "ui.jump.dist",  "{0:F1} ly" },
        { "ui.jump.cost",  "{0:F0} H" },
        { "ui.jump.time",  "{0:F0} d" },
        { "ui.jump.back",  "back {0:F0} H" },
        { "ui.jump.go",    "JUMP" },

        // Wake conditions
        { "ui.wake",       "WAKE CONDITIONS" },
        { "ui.wake.hint",  "Time warp drops to x1 when one trips." },
        { "ui.wake.new",   "New contact" },
        { "ui.wake.lost",  "Contact lost" },
        { "ui.wake.power", "Power below" },
        { "ui.wake.loud",  "Contact louder than" },
        { "wake.new",      "WAKE: new contact {0}" },
        { "wake.lost",     "WAKE: contact {0} lost" },
        { "wake.loud",     "WAKE: {0} at {1:F0} sigma" },
        { "wake.power",    "WAKE: power at {0:F0}%" },

        // Rename / sector / reactor
        { "ui.track.name",      "Name" },
        { "ui.track.namehint",  "select a track" },
        { "ui.wake.sector",     "Limit new/loud contacts to a sector" },
        { "ui.wake.center",     "Center" },
        { "ui.wake.width",      "Half-width" },
        { "ui.wake.ontrack",    "On track" },
        { "ui.reactor",         "REACTOR" },
        { "ui.reactor.off",     "OFF" },
        { "ui.reactor.info",    "+{0:F2} power/day, burns {1:F3} H/day" },

        // Data / recording
        { "ui.data",            "DATA" },
        { "ui.data.sel",        "Selected: {0}" },
        { "ui.data.nosel",      "Select a confirmed track to record it." },
        { "ui.data.stub",       "Log stub" },
        { "ui.data.raw",        "Record raw" },
        { "ui.data.rawstop",    "Stop raw" },
        { "ui.data.compress",   "Compressed" },
        { "ui.data.free",       "Free {0:F1} / {1:F0}    value on board {2:F1}" },
        { "ui.data.none",       "Nothing recorded." },
        { "ui.data.dump",       "x" },
        { "ui.data.kind.stub",  "stub" },
        { "ui.data.kind.raw",   "raw" },
        { "ui.data.kind.rawc",  "raw (c)" },
        { "ui.data.rowname",    "{0}  {1}  {2}" },
        { "ui.data.size",       "{0:F1} u" },
        { "ui.data.value",      "v {0:F1}" },
        { "ui.data.rec",        "REC" },
        { "ui.data.lost",       "track lost" },
        { "ui.data.full",       "full" },
        { "debrief.data",       "Data on board: {0} records, value {1:F1}, storage {2:F1}." },

        // Transmitter
        { "ui.tx",              "TRANSMIT HOME" },
        { "ui.tx.dist",         "Home is {0:F3} ly away" },
        { "ui.tx.level",        "Power" },
        { "ui.tx.robust",       "Robust coding" },
        { "ui.tx.margin",       "Link margin {0:+0.0;-0.0} dB   (about {1:F0}% of packets lost)" },
        { "ui.tx.energy",       "Cost {0:F1} power per data unit sent" },
        { "ui.tx.hint",         "Sending keeps your copy. What arrived is only known at debrief." },
        { "ui.tx.count",        "Sent this run: {0} transmissions" },
        { "ui.tx.send",         "tx" },
        { "ui.tx.sent",         "sent {0}" },
        { "tx.power",           "Not enough power to transmit that." },
        { "debrief.tx",         "Transmitted {0} times: {1} of {2} packets got through, value received {3:F1}." },
        { "debrief.gasp",       "The dying probe sent {0} record(s) with its last reserve." },
        { "debrief.returned",   "Carried home: value {0:F1}." },
        { "debrief.total",      "Total value recovered: {0:F1}." },

        // Atlas
        { "ui.atlas",           "ATLAS" },
        { "ui.atlas.count",     "ATLAS ({0})" },
        { "ui.atlas.none",      "Nothing logged yet." },
        { "ui.atlas.col.system","SYSTEM" },
        { "ui.atlas.col.name",  "NAME" },
        { "ui.atlas.col.kind",  "KIND" },
        { "ui.atlas.col.value", "VALUE" },
        { "ui.atlas.col.status","STATUS" },
        { "ui.atlas.run",       "run {0}" },
        { "ui.atlas.wrong",     "DISPUTED" },
        { "ui.atlas.corrected", "CORRECTED" },
        { "ui.atlas.conf.t",    "tentative" },
        { "ui.atlas.conf.c",    "confirmed" },
        { "ui.data.conf.t",     "T" },
        { "ui.data.conf.c",     "C" },
        { "rev.reward",         "{0} entries filed, value {1:F1}" },
        { "rev.corrected",      "{0} ({1}) corrected by a new survey" },
        { "rev.caught.t",       "tentative {0} ({1}) found wrong, value {2:F1} withdrawn" },
        { "rev.caught.c",       "CONFIRMED {0} ({1}) found wrong, value {2:F1} withdrawn" },
        { "ui.system.trust",    "SYSTEM {0}   TRUST {1:F0}" },
        { "rev.lost",           "probe lost" },
        { "debrief.trust",      "Trust {0:F1} -> {1:F1}  ({2:+0.0;-0.0})" },
        { "debrief.review",     "Review: {0} entries checked, {1} disputed, {2} corrected" },
        { "debrief.change",     "{0:+0.0;-0.0}  {1}" },
        { "ui.atlas.catalogued","CATALOGUE" },
        { "ui.atlas.home",        "HOME" },
        { "ui.atlas.page",        "page {0}/{1}" },
        { "ui.atlas.unidentified","Unidentified contacts" },
        { "ui.atlas.notsurveyed", "not surveyed" },
        { "ui.atlas.nosurvey",    "No survey data of our own yet." },
        { "ui.atlas.recall",       "RECALL (known orbit)" },
        { "ui.atlas.recall.orbit","RECALL (determined orbit)" },
        { "ui.atlas.recall.rough","RECALL (rough, aged fix)" },
        { "ui.atlas.recall.none", "RECALL (no fix on file)" },
        { "ui.atlas.recall.done", "{0} seeded - check TRACKS / NAV / a sensor's SEL." },
        { "ui.atlas.recall.full", "Track list full: drop one first." },
        { "ui.atlas.col.bodies",  "BODIES" },
        { "ui.atlas.col.entries", "ENTRIES" },
        { "ui.atlas.col.contact", "CONTACT" },
        { "ui.atlas.col.run",     "RUN" },
        { "ui.atlas.d.star",      "star, type {0}   T {1:F0} K   [Fe/H] {2:+0.00;-0.00}   age {3:F1} Gyr" },
        { "ui.atlas.d.body",      "{0}   T eq {1:F0} K   surface {2:F0} K" },
        { "ui.atlas.d.moonof",    "moon of {0}" },
        { "ui.atlas.d.phys",      "mass {0:G3} Earth   radius {1:G3} Earth   albedo {2:F2}" },
        { "ui.atlas.d.orbit",     "orbit a {0}   e {1:F3}   i {2:F1} deg   period {3:F1} d" },
        { "ui.atlas.d.comp",      "composition: {0}" },
        { "ui.atlas.d.atmo",      "atmosphere {0:G3} atm: {1}" },
        { "ui.atlas.d.envelope",  "envelope: {0}" },
        { "ui.atlas.d.airless",   "no atmosphere" },
        { "ui.data.known",      "known: {0}" },

        // Debrief
        { "debrief.title",       "DEBRIEF" },
        { "debrief.run",         "Run #{0}" },
        { "debrief.cause.power", "The probe ran out of power." },
        { "debrief.cause.home",  "The probe returned home." },
        { "debrief.duration",    "Survived {0:F1} days." },
        { "debrief.relaunch",    "Refit next probe" },
        { "refit.title",         "PROBE REFIT" },
        { "refit.hint",          "Home lends hardware by trust. Everything is on offer; the total cost must fit the budget." },
        { "refit.budget",        "Trust {0:F1}   —   used {1} of {2} points" },
        { "refit.sensors",       "SENSORS" },
        { "refit.modules",       "PROBE MODULES" },
        { "refit.navigation",    "NAVIGATION" },
        { "refit.back",          "BACK TO DEBRIEF" },
        { "refit.baseline",      "BASELINE" },
        { "refit.launch",        "LAUNCH" },
        { "refit.over",          "Over budget by {0} point(s): lower something to launch." },
        { "refit.warn.spectro",  "The spectrometer needs a fine elevation to point its slit: fit the imager (FIX) or the radar (TRACK ping)." },
        { "refit.none",          "not fitted" },
        { "refit.lvl.none",      "NONE" },
        { "refit.lvl.stock",     "STOCK" },
        { "refit.lvl.1",         "MK I" },
        { "refit.lvl.2",         "MK II" },
        { "refit.lvl.3",         "MK III" },
        { "refit.sys.waterfall",    "Waterfall" },
        { "refit.sys.imager",       "Imager" },
        { "refit.sys.spectrometer", "Spectrometer" },
        { "refit.sys.radar",        "Radar" },
        { "refit.sys.battery",      "Battery" },
        { "refit.sys.tank",         "H2 tank" },
        { "refit.sys.storage",      "Storage" },
        { "refit.sys.transmitter",  "Transmitter" },
        { "refit.sys.navcomputer",  "Nav computer" },
        { "refit.d.waterfall",   "beam {0:F2}°  ·  min signal {1:F1}  ·  {2} tracks  ·  {3:F1} power/d" },
        { "refit.d.imager",      "min FOV {0:F2}° (÷10 zoomed)  ·  noise {1:F2}  ·  {2}-frame integrator  ·  {3:F1} power/d" },
        { "refit.d.spectro",     "R {0:F0}  ·  resolves {1:F0} km/s  ·  {2:F1} power/d" },
        { "refit.d.radar",       "reach ~{0:F0} AU (Earth-size)  ·  track beam {1:F3}°  ·  {2:F1} per ping" },
        { "refit.d.battery",     "{0:F0} power" },
        { "refit.d.tank",        "{0:F0} H2  ({1:F0} km/s)" },
        { "refit.d.storage",     "{0:F0} storage" },
        { "refit.d.tx",          "range {0:F1} ly  ·  {1:F1} units/d" },
        { "refit.d.nav.0",       "no NAV screen - orbit and jump planning stay text-only" },
        { "refit.d.nav.1",       "system view: ship orbit, Pe/Ap/AN/DN, single-node preview" },
        { "refit.d.nav.2",       "+ transfer planner on the map, galaxy map" },
        { "refit.d.nav.3",       "+ orbit fits for tracked bodies from their history" },

        // Menus
        { "menu.title",          "SPACESHIP BRIDGE" },
        { "menu.subtitle",       "Passive and active sensing, one probe at a time" },
        { "menu.newgame",        "NEW GAME" },
        { "menu.settings",       "SETTINGS" },
        { "menu.quit",           "QUIT" },
        { "menu.lastseed",       "World seed {0}" },
        { "menu.seed",           "WORLD SEED" },
        { "menu.seed.hint",      "The same seed always builds the same galaxy." },
        { "menu.seed.random",    "RANDOM" },
        { "menu.newgame.warn",   "This ends the current expedition: atlas, trust, tracks and clock start over." },
        { "menu.start",          "START" },
        { "menu.continue",       "CONTINUE" },
        { "menu.save",           "SAVE GAME" },
        { "menu.load",           "LOAD GAME" },
        { "menu.save.do",        "SAVE" },
        { "menu.delete",         "DELETE" },
        { "menu.slotname",       "NAME" },
        { "menu.slotname.hint",  "slot name" },
        { "menu.slotname.default","Expedition {0}" },
        { "menu.slotname.empty", "Type a name for the save first." },
        { "menu.slot",           "{0}   -   run {1}, day {2:F1}, {3}   ({4}){5}" },
        { "menu.slot.debrief",   "  [debrief]" },
        { "menu.slot.refit",     "  [refit]" },
        { "menu.noslots",        "No saved games yet." },
        { "menu.saved",          "Saved as \"{0}\"." },
        { "menu.save.failed",    "Save failed: {0}" },
        { "menu.save.nothing",   "Nothing to save: no expedition in progress." },
        { "menu.load.failed",    "Load failed: {0}" },
        { "menu.deleted",        "Deleted \"{0}\"." },
        { "menu.confirm.overwrite", "Overwrite the save \"{0}\"?" },
        { "menu.confirm.delete", "Delete the save \"{0}\"? This cannot be undone." },
        { "menu.confirm.load",   "Load this save? Progress since your last save will be lost." },
        { "menu.back",           "BACK" },
        { "menu.paused",         "PAUSED" },
        { "menu.resume",         "RESUME" },
        { "menu.mainmenu",       "MAIN MENU" },
        { "menu.confirm.abandon","Abandon this expedition and return to the main menu? There is no save yet." },
        { "menu.confirm.quit",   "Quit the game? The expedition is not saved." },
        { "menu.yes",            "YES" },
        { "menu.no",             "NO" },
        { "menu.tab.display",    "DISPLAY" },
        { "menu.tab.time",       "TIME" },
        { "menu.tab.controls",   "CONTROLS" },

        // Settings
        { "set.uiscale",         "UI SCALE" },
        { "set.uiscale.value",   "{0:F0}%" },
        { "set.textsize",        "TEXT SIZE" },
        { "set.text.small",      "SMALL" },
        { "set.text.normal",     "NORMAL" },
        { "set.text.large",      "LARGE" },
        { "set.theme",           "THEME" },
        { "set.theme.phosphor",  "PHOSPHOR" },
        { "set.theme.amber",     "AMBER" },
        { "set.theme.cyan",      "CYAN" },
        { "set.theme.highcontrast","HI-CONTRAST" },
        { "set.display.hint",    "Theme and text size redraw the whole console; sensors keep running." },
        { "set.defaultwarp",     "WARP AT LAUNCH" },
        { "set.startpaused",     "START RUNS PAUSED" },
        { "set.focuspause",      "PAUSE ON FOCUS LOSS" },
        { "set.on",              "ON" },
        { "set.off",             "OFF" },
        { "set.time.hint",       "Applied to every new probe. In flight: warp keys step the same ladder." },
        { "set.resetkeys",       "RESET DEFAULT KEYS" },
        { "set.presskey",        "press a key..." },
        { "set.controls.hint",   "Click a slot to rebind it. A key can only do one thing." },
        { "set.capture.hint",    "Press the new key. Esc cancels, Backspace clears the slot." },
        { "act.aimleft",         "AIM LEFT" },
        { "act.aimright",        "AIM RIGHT" },
        { "act.aimup",           "AIM UP" },
        { "act.aimdown",         "AIM DOWN" },
        { "act.fine",            "FINE AIM (hold)" },
        { "act.confirm",         "CONFIRM / PING" },
        { "act.pause",           "PAUSE" },
        { "act.warpup",          "WARP UP" },
        { "act.warpdown",        "WARP DOWN" },
        { "act.menu",            "MENU" },
    };

    /// <summary>A distance given in AU, in the unit that reads best: km below 0.01 AU (planet orbits), AU above.</summary>
    public static string Distance(double au)
    {
        if (double.IsInfinity(au) || double.IsNaN(au)) return "-";
        if (au < 0.01) return (au * 1.495978707e8).ToString("N0") + " km";
        return au.ToString(au < 10 ? "F2" : "F1") + " AU";
    }

    /// <summary>A duration in simulated seconds, as D:HH:MM:SS (the day segment dropped under 24h) - a plain
    /// "x.x d" reads as roughly-a-day-and-a-bit right up until the burn, which is exactly the useless moment
    /// for a countdown (waiting for the last seconds before an armed node fires). Negative/NaN clamp to 0.</summary>
    public static string Countdown(double seconds)
    {
        if (double.IsNaN(seconds)) return "-";
        long total = (long)Math.Round(Math.Max(0.0, seconds));
        long d = total / 86400; total -= d * 86400;
        long h = total / 3600;  total -= h * 3600;
        long m = total / 60;    long s = total - m * 60;
        return d > 0 ? $"{d}:{h:00}:{m:00}:{s:00}" : $"{h:00}:{m:00}:{s:00}";
    }

    public static string Get(string key, params object[] args)
    {
        string s;
        if (!English.TryGetValue(key, out s)) return "[" + key + "]";
        return args != null && args.Length > 0 ? string.Format(s, args) : s;
    }
}
