using System.Collections.Generic;

/// <summary>
/// Real spectral line reference data, restricted to the visible band the spectrometer currently covers
/// (GameConstants.SPECTRUM_WAVELENGTH_MIN..MAX, ~380-780nm). SystemFactory.DetermineSpectrum looks a
/// composition element up here instead of inlining wavelengths, and SpectrometerScreen's overlay reads
/// the wavelength back to a label from the same SpectralLine.species field DetermineSpectrum sets from
/// this table - so the two are always in sync by construction, never by two copies of the same numbers.
///
/// Honesty note, since this is meant to be a serious sim: H, He, Na, Mg, Ca and Fe below are real,
/// well-established visible-band transitions - the Balmer series, the He I "D3" line, the Na D doublet,
/// the Mg "b" triplet, Ca II H&amp;K, and a representative handful of Fe I lines (culminating in the
/// classic Fraunhofer "E" line at 527nm). O, C, Si, Al and N do NOT have strong resolved atomic lines in
/// the visible band in reality - their prominent transitions sit in the UV or IR - so those five keep
/// placeholder wavelengths purely so every element SystemFactory currently generates still shows
/// *something* on a visible-only instrument, flagged `real = false` below. Worth replacing once a second
/// instrument (or an extended spectrometer band) covers UV/IR - see the chemistry/geology pass.
/// </summary>
public static class SpectralLineTable
{
    public struct Line
    {
        public float wavelength; // nm
        public bool  emission;   // true = emission, false = absorption
        public float weight;     // relative strength within this element's OWN line set, (0, 1]
        public bool  real;       // a genuine cataloged transition vs. a gameplay placeholder (see class doc)
    }

    private static readonly Dictionary<string, Line[]> Lines = new Dictionary<string, Line[]>
    {
        ["H"] = new[]
        {
            new Line { wavelength = 656.28f, emission = true,  weight = 1.00f, real = true }, // H-alpha
            new Line { wavelength = 486.13f, emission = true,  weight = 0.70f, real = true }, // H-beta
            new Line { wavelength = 434.05f, emission = false, weight = 0.45f, real = true }, // H-gamma
            new Line { wavelength = 410.17f, emission = false, weight = 0.25f, real = true }, // H-delta
        },
        ["He"] = new[]
        {
            new Line { wavelength = 587.56f, emission = true, weight = 1.00f, real = true }, // D3
            new Line { wavelength = 667.82f, emission = true, weight = 0.35f, real = true },
        },
        ["Na"] = new[]
        {
            new Line { wavelength = 589.00f, emission = false, weight = 1.00f, real = true }, // D2
            new Line { wavelength = 589.59f, emission = false, weight = 0.95f, real = true }, // D1 - a close
            // doublet on purpose: a low resolving-power spectrometer blends these into one feature.
        },
        ["Mg"] = new[]
        {
            new Line { wavelength = 516.73f, emission = false, weight = 0.70f, real = true }, // b4
            new Line { wavelength = 517.27f, emission = false, weight = 1.00f, real = true }, // b2
            new Line { wavelength = 518.36f, emission = false, weight = 0.85f, real = true }, // b1 - the "b" triplet
        },
        ["Ca"] = new[]
        {
            new Line { wavelength = 393.37f, emission = false, weight = 1.00f, real = true }, // K
            new Line { wavelength = 396.85f, emission = false, weight = 0.90f, real = true }, // H
            // Not currently generated by DetermineChemicalComposition (no body type includes Ca yet) - kept
            // ready for the crust-composition pass, since Ca II H&K are some of the most recognizable lines
            // in real stellar/planetary spectroscopy.
        },
        ["Fe"] = new[]
        {
            new Line { wavelength = 438.35f, emission = false, weight = 0.55f, real = true },
            new Line { wavelength = 466.81f, emission = false, weight = 0.45f, real = true },
            new Line { wavelength = 495.76f, emission = false, weight = 0.50f, real = true },
            new Line { wavelength = 527.04f, emission = false, weight = 1.00f, real = true }, // Fraunhofer "E"
        },

        // Placeholders (see class doc): not real visible-band atomic lines, kept so every element the
        // generator produces still shows up on a visible-only scan.
        ["O"]  = new[] { new Line { wavelength = 777.4f, emission = false, weight = 1f, real = false } },
        ["C"]  = new[] { new Line { wavelength = 477.0f, emission = false, weight = 1f, real = false } },
        ["Si"] = new[] { new Line { wavelength = 634.7f, emission = false, weight = 1f, real = false } },
        ["Al"] = new[] { new Line { wavelength = 396.2f, emission = false, weight = 1f, real = false } },
        ["N"]  = new[] { new Line { wavelength = 388.4f, emission = false, weight = 1f, real = false } },
    };

    public static bool TryGet(string element, out Line[] lines) => Lines.TryGetValue(element, out lines);
}
